version: '3.2'
services:
  rabbitmq:
    image: rabbitmq:3.10.6-management-alpine
    container_name: 'rabbitmq'
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ~/.docker-conf/rabbitmq:/var/lib/rabbitmq/mnesia'
    networks:
      - messaging_net
networks:
  messaging_net:
    driver: bridge